### ISSUE TITLE
issue with HTML / exhibit parsing

### ISSUE THREAD

**Issue by erimille** [zepheira/backstage#13]
working on icd9 backstage demonstration i'm seeing odd behavior when changing the HTML / exhibit structure. 

Given a sample lens

```
<div ex:role="exhibit-lens" class="a-lens" onmouseover="mouseOver(this);" onmouseout="mouseOut(this);">
  <div class="title"><span ex:content=".label"></span></div>
  <div>Kind: <span ex:content=".kind"></span></div>
  <div>Inclusion: <span ex:content=".inclusion"></span></div>
  <div>Subclass of: <span ex:content=".subclasses.label"></span></div>
  <div>Superclass of: <span ex:content=".superclasses.label"></span></div>
  <div class="identifier">Identifier: <span ex:content=".id"></span></div>
</div>
```

and then adding an <hr /> into this ... e.g. 

```
<div ex:role="exhibit-lens" class="a-lens" onmouseover="mouseOver(this);" onmouseout="mouseOut(this);">
  <div class="title"><span ex:content=".label"></span></div>
  <div>Kind: <span ex:content=".kind"></span></div>
  <div>Inclusion: <span ex:content=".inclusion"></span></div>
  <div>Subclass of: <span ex:content=".subclasses.label"></span></div>
  <div>Superclass of: <span ex:content=".superclasses.label"></span></div>
  <hr />
  <div class="identifier">Identifier: <span ex:content=".id"></span></div>
</div>
```

hangs the backstaged exhibit.

I've seen similar behavior when changing around the HTML structure. I narrowed the problem down to this simple change, but i suspect its a bigger issue.

Flagging this as nothing will frustrate users more than simple stylistic / structural changes to HTML breaking their exhibit.

**Comment by erimille** [comment]
adding an additional span tag (below) for css invokes a similar hang

```
<div ex:role="exhibit-lens" class="a-lens" onmouseover="mouseOver(this);" onmouseout="mouseOut(this);">
  <div class="title"><span ex:content=".label"></span></div>
  <div><span class="property kind">Kind:</span> <span ex:content=".kind"></span></div>
  ...
```

   </div>

I'm thinking this issue may in fact be related to https://github.com/zepheira/backstage/issues/6 and the hanging based on the additional nested elements is preventing execution on some of the additional exhibit bits.

**Comment by distobj** [comment]
I forgot to update this issue with something I learned while debugging it a couple of weeks ago.  The problem only manifests after a session has already been initialized, so it is not related to parsing the configuration DOM.  You can demonstrate this by starting the server, viewing an exhibit, modifying the exhibit HTML (e.g. lens DOM), and starting another viewing session - at which point the bug is observed (through errors in the console). But if you then restart the server and freshly view the exhibit, it works correctly.

**Comment by zepheiryan** [comment]
The issue appears to be modifying lenses after a session has already been initiated.  It may relate to other components, but it certainly appears with lenses.  Specifically, when the shape of the lens starts to grow larger than the initial shape; if your lens has three content properties and you change any of them to other properties, things will still work.  If you add a fourth property, things will hang.  It is likely there are other "shape changing" modifications that will bring about the same behavior.

Lenses are cached. `edu.mit.simile.backstage.model.data.Database.cacheAndRun`, `edu.mit.simile.backstage.model.data.Database.ViewRenderingCacheableQuery`, and `edu.mit.simile.backstage.model.data.CacheableQuery` are good places to start.

I suggest having a development mode, with some nagging visual indicator about being in development mode, where nothing of this nature is cached and Backstage users can design until satisfied before utilizing the performance tricks.

**Comment by distobj** [comment]
This turns out to be by design; Backstage doesn't support editing of exhibit HTML after sessions have been established.  Issue #25 has been created as a workaround.
