### ISSUE TITLE
Wiki: Path for exhibit files wrong?

### ISSUE THREAD

**Issue by dominikb1888** [zepheira/backstage#20]
One difference towards the manual I've experienced while testing backstage. The path for to exhibit-api.js which is listed under authoring for me was: http://localhost:8181/exhibit/api/exhibit-api.js?autoCreate=false&amp;postLoad=true&amp;js=http://localhost:8181/backstage/api/backstage-api.js

Seems like butterfly is exposing the exhibit files directly in root, not in http://localhost:8181/backstage/exhibit... as mentioned in the wiki.

**Comment by distobj** [comment]
Thanks for catching that, Domink. I've updated the Wiki.

**Comment by zepheiryan** [comment]
I'd forgotten that was the case, it should probably move back to being mounted at /backstage/exhibit/api instead.  Part of the point of putting everything under /backstage was to make proxying simple.

**Comment by distobj** [comment]
Ryan, did you want to preserve the "main" module, or to revert?

**Comment by zepheiryan** [comment]
Fixed in 891da38305f9ef5108450daac8be3ce1f5c3c31f

**Comment by zepheiryan** [comment]
The new Butterfly seems to have modified its mount algorithm such that Backstage won't run at /backstage (only at /) without the otherwise empty main module.
