### ISSUE TITLE
main class not loading

### ISSUE THREAD

**Issue by arjundatt** [zepheira/backstage#35]
I tried to build backstage exactly according to the installation procedures mentioned and all went fine unless, when I started executing by   ./backstage
It gives an error as:

Starting Butterfly at 'http://localhost:8181/'
Error:Could not find or load main class edu.mit.simile.butterfly.ButterflyServer  

I found the aforementioned class in the server.classes dir but somehow it doesn't load.

**Comment by distobj** [comment]
Hi. I know that others have tried these same instructions and were able to get it working.  What OS are you using? Java version?  Would you mind retrying the steps one more time (being sure to cleanup from the previous install)? Thanks.

**Comment by arjundatt** [comment]
Hi,
Well, I am using Windows 7 and java version 7. Could you please tell me, to what exact value should JAVA_HOME be set. I might have done a mistake there! Here is my directory structure:
C:\Progra~1\Java<here is my java>
C:\Users\Operator\e3src<here are all the directories from the installation>

PS: I am a young programmer, so pardon me if this is a trivial mistake.

**Comment by distobj** [comment]
Ah. Unfortunately, we don't support Windows right now, though I believe that the only thing missing is the porting of the backstage and butterfly batch scripts (an issue has been registered with the butterfly project about theirs).
