### ISSUE TITLE
Java & installation issue

### ISSUE THREAD

**Issue by caprenter** [zepheira/backstage#37]
I've just had a go at installing this on ubuntu 12.10 using java-1.7.0-openjdk-i386

I was getting the error:
"Butterfly requires Java version 6 or later."
So I altered line 458 of /butterfly/butterfly:
- JAVA_VERSION=`$JAVA -version 2>&1 | grep version | cut -d ' ' -f 3 | egrep ^\"1\.6`
- JAVA_VERSION=`$JAVA -version 2>&1 | grep version | cut -d ' ' -f 3 | egrep ^\"1\.7`

and then everything seems fine!

I guess this is a Butterfly issue more than a Backstage issue, but as I encountered it when trying to get Backstage up and running I thought I'd report it. Hope that's ok.

**Comment by distobj** [comment]
Thanks! I've updated the build instructions on the wiki.

If you haven't already, please also register this as an issue with Butterfly.

**Comment by caprenter** [comment]
Thanks also reported to Butterfly issue queue:
http://code.google.com/p/simile-butterfly/issues/detail?id=9
